databases:
  - name: airline-postgres
    plan: free
    databaseName: airlinedb
    user: airline

services:
  - type: redis
    name: airline-redis
    plan: free
    ipAllowList: [] # Empty list restricts access to internal Render services only

  - type: web
    name: airline-api-gateway
    env: docker
    dockerfilePath: ApiGateway/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}

  - type: web
    name: auth-api
    env: docker
    dockerfilePath: Auth.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}

  - type: web
    name: flight-search-api
    env: docker
    dockerfilePath: Flight.Search.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: airline-postgres
          property: connectionString
      - key: ConnectionStrings__Redis
        fromService:
          type: redis
          name: airline-redis
          property: connectionString

  - type: web
    name: booking-api
    env: docker
    dockerfilePath: Booking.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: airline-postgres
          property: connectionString
      - key: ConnectionStrings__Redis
        fromService:
          type: redis
          name: airline-redis
          property: connectionString

  - type: web
    name: payment-api
    env: docker
    dockerfilePath: Payment.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}

  - type: web
    name: passenger-api
    env: docker
    dockerfilePath: Passenger.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: airline-postgres
          property: connectionString

  - type: web
    name: admin-api
    env: docker
    dockerfilePath: Admin.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: airline-postgres
          property: connectionString

  - type: web
    name: staff-operations-api
    env: docker
    dockerfilePath: Staff.Operations.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: airline-postgres
          property: connectionString

  - type: worker
    name: notification-worker
    env: docker
    dockerfilePath: Notification.Worker/Dockerfile
    plan: free
