// <auto-generated />
using FoodInventory.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodInventory.API.Migrations
{
    [DbContext(typeof(FoodInventoryDbContext))]
    [Migration("20260428072449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodInventory.API.Models.FoodItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = "F001",
                            Category = "Meal",
                            Name = "Vegetarian Sandwich",
                            Price = 250m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = "F002",
                            Category = "Meal",
                            Name = "Chicken Wrap",
                            Price = 300m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = "B001",
                            Category = "Beverage",
                            Name = "Coffee",
                            Price = 100m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = "B002",
                            Category = "Beverage",
                            Name = "Water Bottle",
                            Price = 50m,
                            StockQuantity = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
